indent = 4
margin = 100
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = true
format_docstrings = true
trailing_comma = "nothing"
